# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  # Path to the Sphinx configuration file.
  configuration: docs/source/conf.py 

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

formats:
  - epub
  - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements.txt
